### ISSUE TITLE
Position Control Tutorial

### ISSUE THREAD

**Issue by zachbons** [neurobionics/opensourceleg#115]
## 🐛 Bug Report

When I run the code in the Position Control Tutorial, nothing happens to the motor (it doesn't change position).

## 🔬 How To Reproduce

1. Type out the code in the tutorial word for word and run on hardware.

### Environment

* OS: 
Windows SSH'd into an RPi (Linux)
* Python version, get it with:
3.9.2

## 📈 Expected behavior

I expect the motor to move to the desired setpoint position

## 📎 Additional context

This is solved by placing osl.update() in the line before osl.knee.set_motor_position(). Also, the set_point description says that it's in 'motor ticks' but I believe it's actually the designated position units.

**Comment by imsenthur** [comment]
@jderosia

**Comment by jderosia** [comment]
Thank you for pointing this out. This pull request should fix that issue. #116

**Comment by imsenthur** [comment]
Merged #116 with `master` [68196600c69b2a4b167c1b23bfb1252f67e346be].
