### ISSUE TITLE
Thermal model units undefined in thermal model update

### ISSUE THREAD

**Issue by tkevinbest** [neurobionics/opensourceleg#122]
This call to update the thermal model uses the user defined units, but the model expects the value in mA. If the user switches to A for the current units, the thermal model will be wrong. 

https://github.com/neurobionics/opensourceleg/blob/68196600c69b2a4b167c1b23bfb1252f67e346be/opensourceleg/actuators.py#L382C1-L384C14

**Comment by imsenthur** [comment]
Fixed! Please checkout the dev branch [39a26c0a4d67534576ba73b9c6e101264d036049].
