### ISSUE TITLE
User supplied ports not working for add joints constructor

### ISSUE THREAD

**Issue by tkevinbest** [neurobionics/opensourceleg#124]
## 🐛 Bug Report

If I pass a port to the addjoint method (knee then ankle), there's something that doesn't work with `port_a`. 
```
elif "ankle" in name.lower():
            self._has_ankle = True

            if self.has_knee:
                port = port_a
```

`port_a` in the above code is undefined if user supplied the port.

**Comment by imsenthur** [comment]
Fixed it by reworking how ports get assigned and added a conditional check to prevent ports from getting overwritten. 

Please checkout the dev branch [c0537831e382feddcb9522c51df6dc29cecce2f1].
