### ISSUE TITLE
Add type checking to logger

### ISSUE THREAD

**Issue by tkevinbest** [neurobionics/opensourceleg#127]
Errors in the logger are very hard to debug. You need to supply names very specifically or you get weird errors. 

This syntax worsk:
`osl.log.add_attributes(torqueSensor, ["torque"])`
but this would fail with a weird error:
`osl.log.add_attributes(torqueSensor, "torque")`

A check in the `add_attributes` method would be very helpful!

**Comment by imsenthur** [comment]
Added a type check to the `add_attributes()` method. It will now raise a `[LOGGER] attributes argument must be a list of strings (example: ['a','b']), not {type(attributes)}` and fail elegantly when a wrong type is passed. 

Please checkout the dev branch [cfb806ca1cdf618813fb31472203a815d76cf6e2].
