### ISSUE TITLE
Logger no longer works with dictionaries

### ISSUE THREAD

**Issue by tkevinbest** [neurobionics/opensourceleg#128]
It is helpful to allow the logger to work with dictionaries as well as objects. This lets you use the `locals()` function to get a dictionary of all local values. 

This version of the logger allows it:
```
def update(self, dataContainersIn):
        if self.save:
            row = []
            for (varGroup, container) in zip(self.varNames, dataContainersIn):
                if type(container) is dict:
                    for var in varGroup:
                        row.append(container.get(var))
                else:
                    for var in varGroup:
                        row.append(getattr(container, var))
            self.csv_writer.writerow(row)
```

I wanted to use this syntax and was unable to: `osl.log.add_attributes(locals(), ["active_test_conditions"])`

**Comment by imsenthur** [comment]
Added support for dict containers! Please checkout the dev branch [34905afbaebfd59bfb6fba6bd2eb8109e4662502].
