### ISSUE TITLE
Rationale for separate `joints.py` file? 

### ISSUE THREAD

**Issue by tkevinbest** [neurobionics/opensourceleg#132]
Is there a reason to have `Joints.py` as a separate file instead of just including the joints class inside `osl.py`? I feel like anything we can do to cut down on files is a good thing. 

Is there a use case for manually instantiating a joint? I see where one might want to manually instantiate an actuator, but it seems like you would always just do the osl object and only add one joint if you only wanted to make a joint.

**Comment by imsenthur** [comment]
I assigned myself to this issue and I'll close it when we successfully generalize various modules within our library.
