### ISSUE TITLE
Move values in `constants.py` pertaining to actpacks to the actuators file. 

### ISSUE THREAD

**Issue by tkevinbest** [neurobionics/opensourceleg#133]
Many of the constants in `constants.py` are specific to the actpack and thus should live within the `actuators.py` file within the `DephyActpack` class. One could imagine adding support for another actuator, in which case having these constants contained within their proper container would be important. 

Similarly, there are items in `control.py` that are ActPack specific that should also be moved.

**Comment by imsenthur** [comment]
Moved _constants_ to **actuators.py** module. Please checkout dev branch [49ea2e94a24af150936cdb9c72cbec192759b1e0].
