### ISSUE TITLE
Error for same port names when in offline mode. 

### ISSUE THREAD

**Issue by tkevinbest** [neurobionics/opensourceleg#136]
I get this error when running in offline mode: 
`WARNING: [OSL] Knee and Ankle joints cant have the same port. Please specify a different port for the ankle joint.`

I created the joints using:
```
osl.add_joint('knee', gear_ratio=9*83/18, port=None, offline_mode=True)
osl.add_joint('ankle',gear_ratio=9*83/18, port=None, offline_mode=True)
```

I think supplying None to both joints should be allowed in this context.

**Comment by imsenthur** [comment]
Fixed this error by removing port overwrite check when `offline_mode` is set to `True`. Please checkout the dev branch [e0ddfc30b585cc8858e11d4bfd6c9e0d3213c4a2].
