### ISSUE TITLE
Unecessary conversion functions in Joints.py

### ISSUE THREAD

**Issue by tkevinbest** [neurobionics/opensourceleg#148]
What is the purpose of the methods `convert_to_joint_impedance`, `convert_to_motor_impedance`, and `convert_to_pid_impedance`? They seem to be doing a combination of converting between real units and dephy's arbitrary units. This seems like duplicate functionality that could be replicated with other existing methods. Unless we have a clear use case for them, I think they should be removed.

**Comment by imsenthur** [comment]
Agreed! Those functions (`convert_to_joint_impedance`, `convert_to_motor_impedance`, and `convert_to_pid_impedance`) will be removed in the next update!
