### ISSUE TITLE
Support for SEAs

### ISSUE THREAD

**Issue by tkevinbest** [neurobionics/opensourceleg#149]
Note - none of the angle calculation code would support SEAs right now. We might want to consider renaming things. For example `joint.output_position` is calculated just via motor angle with gear ratio. If there's an SEA in the mix, that might be misleading. I'm not sure the best way to handle this, but we can talk about it. Just wanted to get it our radar.

**Comment by imsenthur** [comment]
Yes! I named it `output_position` because there is another attribute called the `joint_position`, which is read from a joint encoder. I think this would be the extent we can go before things get too complicated. We can improve our documentation to convey this better.
