### ISSUE TITLE
Encoder map method is missing details. 

### ISSUE THREAD

**Issue by tkevinbest** [neurobionics/opensourceleg#217]
## 🐛 Bug Report

The encoder map creation method should announce which joint you need to move. It would also be good if it kept the old instructions to print out that tell you to move the joint through the full ROM. 
```
 print('Manually move ' + self.name + ' through entire range of motion. \nYou have 10 seconds. Move it around a bunch')
```

## 🔬 How To Reproduce

`osl.ankle.make_encoder_map()`

**Comment by imsenthur** [comment]
Changing `"[{self.__repr__()}] Please manually move the joint numerous times through its full range of motion for 10 seconds. \n{input('Press any key when you are ready to start.')}"` 

to `"[{self.__repr__()}] Please manually move the {self.name} joint numerous times through its full range of motion for 10 seconds. \n{input('Press any key when you are ready to start.')}"`

While the previous log statement had `__repr__` prefixed to it, which is not-so-readable and blends in with all the other log statements, this change adds the joint name to the statement in addition to the `__repr__` prefix. This will be made better with new `__repr__` methods throughout the library in the future.
