### ISSUE TITLE
Test cases fail because of missing abstract method in Mock classes

### ISSUE THREAD

**Issue by imsenthur** [neurobionics/opensourceleg#301]
## 🐛 Bug Report

* Test cases within robots_base and sensors_base fail because of missing `data` method in mock classes
* I guess that this `data` abstract method got added recently before @esharnow started developing tests

### Screenshots
<img width="1040" alt="Screenshot 2024-11-04 at 12 03 24 PM" src="https://github.com/user-attachments/assets/bbeb336a-0054-46e7-aa99-f4e328c1681d">

**Comment by esharnow** [comment]
Added data abstract method to Mock Sensor class in test_sensors_base.py test file. My most recent pull request includes this updated change.
